language: c
script: asdf plugin-test php https://github.com/odarriba/asdf-php.git
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype bison27 gettext icu4c jpeg libpng openssl readline homebrew/dupes/zlib curl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force bison27; fi
  - curl -s https://api.github.com/repos/php/php-src/git/refs/tags | grep '"ref":' | grep 'php-' | grep -Ev "beta|alpha|RC" | sed 's/\"ref\"://' | sed 's/\"refs\/tags\/php-//' | sed 's/\",//'
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install curl build-essential autoconf libjpeg-dev libpng12-dev openssl libssl-dev libcurl4-openssl-dev pkg-config libsslcommon2-dev libreadline-dev libedit-dev zlib1g-dev libicu-dev libxml2-dev gettext bison libmysqlclient-dev libpq-dev -y; fi
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
